# Generated by Django 4.2.7 on 2023-12-01 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0002_user_is_swerc_eligible"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_swerc_eligible",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text='\n        Not mandatory. See <a href="https://icpc.global/regionals/rules"\n        target="_blank">eligibility criteria</a> and <a href="https://swerc.eu/"\n        target="_blank">information about SWERC</a> and check this box if you\n        would be interested in participating to SWERC.',
                verbose_name="I am eligible for SWERC",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="subscribed",
            field=models.BooleanField(
                default=True,
                help_text="Needed to receive contest access credentials.",
                verbose_name="Subscribe to email updates",
            ),
        ),
    ]
