# Generated by Django 4.2.7 on 2023-12-01 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0003_alter_user_is_swerc_eligible_alter_user_subscribed"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="credentials",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
